/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/market/alpha-market-data/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Alpha Metrics */
        post: operations["compute_alpha_metrics_api_market_alpha_market_data__symbol__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload/upload-csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Csv */
        post: operations["upload_csv_api_upload_upload_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_csv_api_upload_upload_csv_post */
        Body_upload_csv_api_upload_upload_csv_post: {
            /** File */
            file: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MarketResponse */
        MarketResponse: {
            /** Timestamps */
            timestamps: string[];
            /** Close */
            close: number[];
            /** Simple Returns */
            simple_returns?: number[] | null;
            /** Log Returns */
            log_returns?: number[] | null;
            /** Sma */
            sma?: number[] | null;
            /** Ema */
            ema?: number[] | null;
            /** Rolling Std */
            rolling_std?: number[] | null;
            /** Annualized Volatility */
            annualized_volatility?: number | null;
            /** Sharpe Ratio */
            sharpe_ratio?: number | null;
            /** Max Drawdown */
            max_drawdown?: number | null;
        };
        /** MetricsRequest */
        MetricsRequest: {
            /**
             * Window
             * @default 20
             */
            window: number;
            /**
             * Risk Free Rate
             * @default 0
             */
            risk_free_rate: number;
            /**
             * Compute Returns
             * @default true
             */
            compute_returns: boolean;
            /**
             * Compute Sma
             * @default true
             */
            compute_sma: boolean;
            /**
             * Compute Ema
             * @default true
             */
            compute_ema: boolean;
            /**
             * Compute Volatility
             * @default false
             */
            compute_volatility: boolean;
            /**
             * Compute Sharpe
             * @default false
             */
            compute_sharpe: boolean;
            /**
             * Compute Drawdown
             * @default false
             */
            compute_drawdown: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    compute_alpha_metrics_api_market_alpha_market_data__symbol__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetricsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_csv_api_upload_upload_csv_post: {
        parameters: {
            query: {
                symbol: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_csv_api_upload_upload_csv_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
